### ISSUE TITLE
not working in hyprland

### ISSUE THREAD

**Issue by obmutescences** [ZacharyL2/KeyEcho#10]
The sound only appears when the mouse is placed inside the dashboard. Not working in any other app.

os info:
   OS : Arch Linux x86_64
   Kernel : Linux 6.9.3-arch1-1
   Packages : 910 (pacman)
   Display : 1920x1080 @ 240Hz
   WM : Hyprland (Wayland)
   Terminal : alacritty 0.14.0-dev
   CPU : 12th Gen Intel(R) Core(TM) i5-12490F
   GPU : GeForce GTX 1050 Ti
   GPU Driver : nvidia 550.90.07
  
  when open the dashboard:
  
  (key-echo:486461): GLib-GObject-WARNING **: 19:31:20.039: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'

(WebKitWebProcess:486517): Gtk-WARNING **: 19:31:20.359: Theme parsing error: gtk-dark.css:6691:68: Invalid name of pseudo-class

(WebKitWebProcess:486517): GLib-GObject-WARNING **: 19:31:20.459: g_object_set_is_valid_property: object class 'GtkSettings' has no property named 'gtk-overlay-scrolling'
/usr/lib/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/tmp/.mount_key-eczPuJgC/usr/lib/libgnutls.so.30: version `GNUTLS_3_7_4' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so

**Comment by ZacharyL2** [comment]
To consolidate the handling of compatibility issues with Non Debian/Ubuntu Linux Distributions, we have opened a new [issue #11](https://github.com/ZacharyL2/KeyEcho/issues/11). Please continue the discussion there. I am closing this issue, thank you for your contributions!

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 updates the Linux listener and packaging, but global keyboard listening on Hyprland/Wayland still needs more testing. The current release ships RPM and DEB packages rather than AppImage. If you are still using Hyprland, please try the v1 RPM. If it still cannot capture key events, open a new issue with your Hyprland, kernel, and XWayland versions plus the startup logs.

**Comment by obmutescences** [comment]
> KeyEcho 1.0 updates the Linux listener and packaging, but global keyboard listening on Hyprland/Wayland still needs more testing. The current release ships RPM and DEB packages rather than AppImage. If you are still using Hyprland, please try the v1 RPM. If it still cannot capture key events, open a new issue with your Hyprland, kernel, and XWayland versions plus the startup logs.

thanks for you working. but i used nixos linux and niri. can`t test without nixos package or appimage package.

**Comment by ZacharyL2** [comment]
Thanks — that’s useful to know. KeyEcho 1.0 no longer ships an AppImage, and there isn’t a NixOS package yet, so there isn’t a straightforward way for you to test it on NixOS + niri right now.

I’m tracking package-manager support in #7. For NixOS, would a package in nixpkgs or a Flake be more useful to you? I’ll keep the packaging discussion there rather than reopen this old Hyprland issue.
