### ISSUE TITLE
(Documentation request) How to build

### ISSUE THREAD

**Issue by hardBSDk** [ZacharyL2/KeyEcho#13]
Add the instructions to build this program on the README.

**Comment by ZacharyL2** [comment]
I've added a brief documentation, and I will provide more details when I have time.

**Comment by Atomized-titan** [comment]
@hardBSDk just do the following:

1. Change directory to `src-tauri`:
    ```sh
    cd src-tauri
    ```
2. Build the project using Cargo:
    ```sh
    cargo build
    ```
3. Run the project using Cargo:
    ```sh
    cargo run
    ```

Then, from the root of the app, run:


    pnpm dev


### Installation Instructions

#### Installing Cargo
Cargo is the package manager for Rust. If you don't have it installed, you can install it by following the instructions in the [Rust documentation](https://doc.rust-lang.org/cargo/getting-started/installation.html).

#### Installing pnpm
pnpm is a fast, disk space-efficient package manager for JavaScript. If you don't have it installed, you can install it by following the instructions in the [pnpm documentation](https://pnpm.io/installation).

**Comment by hardBSDk** [comment]
@Atomized-titan Can you create a PR to add your build instructions on the README?

**Comment by Atomized-titan** [comment]
> @Atomized-titan Can you create a PR to add your build instructions on the README?

PR Raised

**Comment by ZacharyL2** [comment]
Thanks for filling in the missing Rust build instructions at the time. KeyEcho 1.0 has since moved to Tauri 2 and SolidJS, and the README and development commands have been updated with it. `Atomized-titan`, your PR gave the project the build entry point it was missing. If you notice anything wrong in the current documentation, please keep pointing it out.
