### ISSUE TITLE
Howto play in firefox and thunderbird etc ?

### ISSUE THREAD

**Issue by JLuc** [ZacharyL2/KeyEcho#2]
On Ubuntu Linux, I launch the appimage and download a set of sounds. 
When the keyecho window has focus, the keyboard sings the choosen tune. 
How can it also play the downloaded scores when typing in other apps ?

**Comment by JLuc** [comment]
AMOF it plays fine in IntelliJ PhpStorm, but not in other apps.

**Comment by ZacharyL2** [comment]
Thanks for your feedback, I'll start looking into it.

**Comment by JLuc** [comment]
I updated the list of OK vs not OK app in previous comment

**Comment by ZacharyL2** [comment]
@JLuc I downloaded and used [key-echo_0.0.2_amd64.deb](https://github.com/ZacharyL2/KeyEcho/releases/download/v0.0.2/key-echo_0.0.2_amd64.deb), and found that it is working properly.

```
$ neofetch --off
OS: Ubuntu 20.04.6 LTS x86_64 
Kernel: 5.13.0-37-generic 
Uptime: 35 mins 
Shell: bash 5.0.17 
```

Maybe you can download the deb package and try installing it.

**Comment by ZacharyL2** [comment]
To consolidate the handling of compatibility issues with Non Debian/Ubuntu Linux Distributions, we have opened a new [issue #11](https://github.com/ZacharyL2/KeyEcho/issues/11). Please continue the discussion there. I am closing this issue, thank you for your contributions!

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 updates the Linux listener and packaging. The current release ships DEB and RPM packages instead of AppImage. You previously found that Firefox, Thunderbird, terminals, and some other apps were not producing key events. If you still use the same Linux setup, a retest with v1 would be useful. Wayland and desktop-environment differences may still affect global keyboard listening, so I do not want to assume the packaging change fixed it.
