### ISSUE TITLE
[bug] Numpad keys not producing sound 

### ISSUE THREAD

**Issue by qfilip** [ZacharyL2/KeyEcho#23]
### OS

Windows

### OS Version

11

### Describe the bug

Numerical pad keys don't produce sound (except Enter ofc). This is also true for insert, home, pgUp, pgDn, end, delete keys.

### Reproduction

Try typing on keys numpad or insert, home, pgUp, pgDn, end, delete.

### Expected behavior

A sound output on keypress.

**Comment by ZacharyL2** [comment]
I have fixed the sound pack configuration in commit f997f848e2d398b2b5c27854429ba32bf2a9f155. Please try re-downloading the sound pack and then enable it again.

**Comment by qfilip** [comment]
Fixed indeed. Nice project btw. Thank you :)

**Comment by ZacharyL2** [comment]
Thanks for confirming that the numpad fix worked on your device. KeyEcho 1.0 is now out with a rewritten keyboard listener and audio path, while keeping the numpad mappings. There is nothing else you need to test for this issue. I just wanted to come back and acknowledge that your confirmation showed the fix was working on real hardware.
